language: python

python:
  - 3.6

services: postgresql

env:
  - DJANGO=2.0

before_install:
  - export DJANGO_SETTINGS_MODULE=project.settings
  - export PYTHONPATH=$HOME/builds/sbrainproject/sbrain
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - gunicorn project.wsgi &