version: '3'

services:
  web:
    container_name: sbrain-django
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    volumes:
      - .:/code
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: sbrain-postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres